use_frameworks!

def kanna_override
    pod 'Kanna', :git => 'https://github.com/drumbart/Kanna.git', :branch => 'develop'
end

target 'SwiftyHTML_Example' do
    # kanna_override
  pod 'SwiftyHTML', :path => '../'

  target 'SwiftyHTML_Tests' do
    inherit! :search_paths

    
  end
end
